# Generated by Django 6.0.3 on 2026-03-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="library",
            new_name="book",
        ),
    ]
